// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -10; // obj_char
global.__objectDepths[1] = -10; // obj_char_boss1
global.__objectDepths[2] = -999; // obj_player
global.__objectDepths[3] = -10; // obj_hostile_1
global.__objectDepths[4] = -10; // obj_friendly_1
global.__objectDepths[5] = -10; // obj_hostile_2
global.__objectDepths[6] = -10; // obj_boss1
global.__objectDepths[7] = 0; // obj_drlane_1
global.__objectDepths[8] = 0; // obj_drlane_2
global.__objectDepths[9] = 0; // obj_Earth
global.__objectDepths[10] = 0; // obj_vopra
global.__objectDepths[11] = 0; // obj_calia
global.__objectDepths[12] = 0; // obj_oprone
global.__objectDepths[13] = 0; // obj_zeria
global.__objectDepths[14] = 0; // obj_gerus
global.__objectDepths[15] = 0; // obj_asprion
global.__objectDepths[16] = 0; // obj_ocreon
global.__objectDepths[17] = -10; // obj_tree_earth
global.__objectDepths[18] = 0; // obj_explore
global.__objectDepths[19] = 0; // obj_newgame
global.__objectDepths[20] = 0; // obj_continue
global.__objectDepths[21] = 0; // obj_skills
global.__objectDepths[22] = 0; // obj_back
global.__objectDepths[23] = 0; // obj_backpause
global.__objectDepths[24] = 0; // shop_asteroidbutton
global.__objectDepths[25] = 0; // obj_btn_menu
global.__objectDepths[26] = 0; // obj_teleport
global.__objectDepths[27] = 0; // obj_shop_back_oprone
global.__objectDepths[28] = 0; // obj_quit
global.__objectDepths[29] = 0; // obj_resume
global.__objectDepths[30] = 0; // obj_resume_boss1
global.__objectDepths[31] = 0; // obj_earthback
global.__objectDepths[32] = 0; // obj_earthlvl1
global.__objectDepths[33] = 0; // obj_earthlvl2
global.__objectDepths[34] = 0; // obj_earthlvl3
global.__objectDepths[35] = 0; // obj_shop_earth
global.__objectDepths[36] = 0; // obj_vopraback
global.__objectDepths[37] = 0; // obj_shop_vopra
global.__objectDepths[38] = 0; // obj_oprone_back
global.__objectDepths[39] = 0; // obj_shop_oprone
global.__objectDepths[40] = 0; // obj_shop_back_earth
global.__objectDepths[41] = 0; // obj_tradeins_earth
global.__objectDepths[42] = 0; // obj_refills_earth
global.__objectDepths[43] = 0; // obj_upgrades_earth
global.__objectDepths[44] = 0; // obj_back_tradeins_earth
global.__objectDepths[45] = 0; // obj_spacecointrade_earth
global.__objectDepths[46] = 0; // obj_asteroidshardtrade_earth
global.__objectDepths[47] = 0; // obj_tradeins_vopra
global.__objectDepths[48] = 0; // obj_refills_vopra
global.__objectDepths[49] = 0; // obj_upgrades_vopra
global.__objectDepths[50] = 0; // obj_shop_back_vopra
global.__objectDepths[51] = 0; // obj_ach_back
global.__objectDepths[52] = 0; // obj_ach_next
global.__objectDepths[53] = 0; // obj_yes_mission2
global.__objectDepths[54] = 0; // obj_no_mission2
global.__objectDepths[55] = 0; // obj_fragement
global.__objectDepths[56] = 0; // obj_savepoint_space
global.__objectDepths[57] = 0; // obj_mana
global.__objectDepths[58] = 0; // obj_chest_closed
global.__objectDepths[59] = 0; // obj_chest_opening
global.__objectDepths[60] = 0; // obj_chest_opened
global.__objectDepths[61] = 0; // obj_health
global.__objectDepths[62] = 0; // obj_spacecoin
global.__objectDepths[63] = 0; // obj_tree
global.__objectDepths[64] = -20; // obj_asteroidHUD
global.__objectDepths[65] = -22; // collectables_display
global.__objectDepths[66] = 0; // obj_asteroid1
global.__objectDepths[67] = 0; // obj_asteroid2
global.__objectDepths[68] = 0; // obj_asteroid3
global.__objectDepths[69] = 0; // obj_asteroid4
global.__objectDepths[70] = 0; // obj_asteroid5
global.__objectDepths[71] = 0; // obj_asteroidshard1
global.__objectDepths[72] = 0; // obj_asteroidshard2
global.__objectDepths[73] = 0; // obj_asteroidshard3
global.__objectDepths[74] = 0; // obj_asteroidshard4
global.__objectDepths[75] = 0; // obj_asteroidshard5
global.__objectDepths[76] = 0; // obj_teleporter
global.__objectDepths[77] = 0; // obj_vendor
global.__objectDepths[78] = -20; // obj_bullet
global.__objectDepths[79] = -10; // obj_enemybullet
global.__objectDepths[80] = 0; // obj_ship_earth
global.__objectDepths[81] = 0; // obj_ship_earthout
global.__objectDepths[82] = 0; // obj_ship_earthin
global.__objectDepths[83] = 0; // obj_ship_vopra
global.__objectDepths[84] = 0; // obj_ship_vopraout
global.__objectDepths[85] = 0; // obj_ship_voprain
global.__objectDepths[86] = 0; // obj_ship_calia
global.__objectDepths[87] = 0; // obj_ship_caliaout
global.__objectDepths[88] = 0; // obj_ship_caliain
global.__objectDepths[89] = 0; // obj_ship_credits
global.__objectDepths[90] = -999; // landingpad_0
global.__objectDepths[91] = 0; // landingpad_1
global.__objectDepths[92] = 0; // obj_solid_block
global.__objectDepths[93] = 0; // obj_lt_openspace
global.__objectDepths[94] = 0; // obj_lt_earthsector
global.__objectDepths[95] = 0; // obj_lt_opronesector
global.__objectDepths[96] = 0; // obj_lt_voprasector
global.__objectDepths[97] = 0; // obj_lt_caliasector
global.__objectDepths[98] = 0; // obj_lt_zeriasector
global.__objectDepths[99] = 0; // obj_lt_gerussector
global.__objectDepths[100] = 0; // obj_lt_asprionsector
global.__objectDepths[101] = 0; // obj_lt_ocreonsector
global.__objectDepths[102] = 0; // cave_entrance1
global.__objectDepths[103] = 1; // pathcorner_tile
global.__objectDepths[104] = 1; // path_tile
global.__objectDepths[105] = 0; // rockwall
global.__objectDepths[106] = 0; // rockend
global.__objectDepths[107] = 0; // rockend_corner
global.__objectDepths[108] = 0; // rockend_side
global.__objectDepths[109] = 0; // rock_insidecorner
global.__objectDepths[110] = 0; // waterfall_middle
global.__objectDepths[111] = 0; // waterfall_bottom
global.__objectDepths[112] = 0; // waterfall_top
global.__objectDepths[113] = 0; // water_tile
global.__objectDepths[114] = 0; // pathend
global.__objectDepths[115] = 0; // shop_earth
global.__objectDepths[116] = 0; // earth_cave_exit
global.__objectDepths[117] = -700; // ach001
global.__objectDepths[118] = 0; // obj_header
global.__objectDepths[119] = -9999; // cutscene1_fadeout
global.__objectDepths[120] = 0; // obj_menuholo
global.__objectDepths[121] = 0; // shiplevel
global.__objectDepths[122] = 0; // collectable_hud
global.__objectDepths[123] = 0; // obj_wolfmask
global.__objectDepths[124] = 0; // obj_caveterrain
global.__objectDepths[125] = 0; // obj_earth1ctrl
global.__objectDepths[126] = 0; // obj_earth1back
global.__objectDepths[127] = 0; // obj_claimearth1
global.__objectDepths[128] = 0; // obj_earth2char
global.__objectDepths[129] = 0; // obj_earth2points20
global.__objectDepths[130] = 0; // obj_earth2points19
global.__objectDepths[131] = 0; // obj_earth2points18
global.__objectDepths[132] = 0; // obj_earth2points17
global.__objectDepths[133] = 0; // obj_earth2points16
global.__objectDepths[134] = 0; // obj_earth2points15
global.__objectDepths[135] = 0; // obj_earth2points14
global.__objectDepths[136] = 0; // obj_earth2points13
global.__objectDepths[137] = 0; // obj_earth2points12
global.__objectDepths[138] = 0; // obj_earth2points11
global.__objectDepths[139] = 0; // obj_earth2points10
global.__objectDepths[140] = 0; // obj_earth2points9
global.__objectDepths[141] = 0; // obj_earth2points8
global.__objectDepths[142] = 0; // obj_earth2points7
global.__objectDepths[143] = 0; // obj_earth2points6
global.__objectDepths[144] = 0; // obj_earth2points5
global.__objectDepths[145] = 0; // obj_earth2points4
global.__objectDepths[146] = 0; // obj_earth2points3
global.__objectDepths[147] = 0; // obj_earth2points2
global.__objectDepths[148] = 0; // obj_earth2points1
global.__objectDepths[149] = 0; // obj_earth2text
global.__objectDepths[150] = 0; // obj_claimearth2
global.__objectDepths[151] = 0; // obj_earth2back
global.__objectDepths[152] = 0; // obj_earth2retry
global.__objectDepths[153] = 0; // obj_earth3data
global.__objectDepths[154] = 0; // obj_earth3char
global.__objectDepths[155] = 0; // obj_earth3text
global.__objectDepths[156] = 0; // obj_claimearth3
global.__objectDepths[157] = 0; // obj_earth3back
global.__objectDepths[158] = 0; // obj_vopra1_back
global.__objectDepths[159] = 0; // skills
global.__objectDepths[160] = 0; // mega_var
global.__objectDepths[161] = 0; // skill_popups
global.__objectDepths[162] = 0; // gp_pause
global.__objectDepths[163] = 0; // gp_pause_boss1
global.__objectDepths[164] = 0; // gp_pauseearth
global.__objectDepths[165] = 0; // gp_menu
global.__objectDepths[166] = 0; // gp_explore
global.__objectDepths[167] = 0; // gp_map
global.__objectDepths[168] = 0; // gp_levelups
global.__objectDepths[169] = 0; // gp_harvlevelmax
global.__objectDepths[170] = 0; // gp_earth
global.__objectDepths[171] = 0; // gp_mission2_choice
global.__objectDepths[172] = 0; // gp_shopearth
global.__objectDepths[173] = 0; // gp_tradeinsearth
global.__objectDepths[174] = 0; // gp_shopvopra
global.__objectDepths[175] = 0; // gp_tradeinsvopra
global.__objectDepths[176] = 0; // obj_menucontroller
global.__objectDepths[177] = -20; // obj_HUDcontroller
global.__objectDepths[178] = 0; // obj_spacesoundctrl
global.__objectDepths[179] = 0; // obj_mapcontroller
global.__objectDepths[180] = 0; // obj_skillsdraw
global.__objectDepths[181] = 0; // shop_values
global.__objectDepths[182] = 0; // shop_draw
global.__objectDepths[183] = -10; // altpause_controller
global.__objectDepths[184] = -10; // altpause_earth
global.__objectDepths[185] = 0; // screenshot_text
global.__objectDepths[186] = -2000; // earthcontroller
global.__objectDepths[187] = 0; // obj_noid_draw
global.__objectDepths[188] = 0; // credits_controller
global.__objectDepths[189] = 0; // object149
global.__objectDepths[190] = 0; // cutscene1_1_tl
global.__objectDepths[191] = 0; // cutscene1_2_tl
global.__objectDepths[192] = 0; // cutscene2_1_tl
global.__objectDepths[193] = 0; // cutscene2_2_tl
global.__objectDepths[194] = 0; // cutscene_m2_1_tl
global.__objectDepths[195] = 0; // cutscene_m2_2_tl
global.__objectDepths[196] = 0; // cutscene_m2_3_tl
global.__objectDepths[197] = 0; // cutscene_controller
global.__objectDepths[198] = -1; // mission_completion
global.__objectDepths[199] = 0; // boss1_healthbar
global.__objectDepths[200] = -34; // planetbar_hud
global.__objectDepths[201] = 0; // quest_earth
global.__objectDepths[202] = 0; // game_saver
global.__objectDepths[203] = 0; // obj_ach001


global.__objectNames[0] = "obj_char";
global.__objectNames[1] = "obj_char_boss1";
global.__objectNames[2] = "obj_player";
global.__objectNames[3] = "obj_hostile_1";
global.__objectNames[4] = "obj_friendly_1";
global.__objectNames[5] = "obj_hostile_2";
global.__objectNames[6] = "obj_boss1";
global.__objectNames[7] = "obj_drlane_1";
global.__objectNames[8] = "obj_drlane_2";
global.__objectNames[9] = "obj_Earth";
global.__objectNames[10] = "obj_vopra";
global.__objectNames[11] = "obj_calia";
global.__objectNames[12] = "obj_oprone";
global.__objectNames[13] = "obj_zeria";
global.__objectNames[14] = "obj_gerus";
global.__objectNames[15] = "obj_asprion";
global.__objectNames[16] = "obj_ocreon";
global.__objectNames[17] = "obj_tree_earth";
global.__objectNames[18] = "obj_explore";
global.__objectNames[19] = "obj_newgame";
global.__objectNames[20] = "obj_continue";
global.__objectNames[21] = "obj_skills";
global.__objectNames[22] = "obj_back";
global.__objectNames[23] = "obj_backpause";
global.__objectNames[24] = "shop_asteroidbutton";
global.__objectNames[25] = "obj_btn_menu";
global.__objectNames[26] = "obj_teleport";
global.__objectNames[27] = "obj_shop_back_oprone";
global.__objectNames[28] = "obj_quit";
global.__objectNames[29] = "obj_resume";
global.__objectNames[30] = "obj_resume_boss1";
global.__objectNames[31] = "obj_earthback";
global.__objectNames[32] = "obj_earthlvl1";
global.__objectNames[33] = "obj_earthlvl2";
global.__objectNames[34] = "obj_earthlvl3";
global.__objectNames[35] = "obj_shop_earth";
global.__objectNames[36] = "obj_vopraback";
global.__objectNames[37] = "obj_shop_vopra";
global.__objectNames[38] = "obj_oprone_back";
global.__objectNames[39] = "obj_shop_oprone";
global.__objectNames[40] = "obj_shop_back_earth";
global.__objectNames[41] = "obj_tradeins_earth";
global.__objectNames[42] = "obj_refills_earth";
global.__objectNames[43] = "obj_upgrades_earth";
global.__objectNames[44] = "obj_back_tradeins_earth";
global.__objectNames[45] = "obj_spacecointrade_earth";
global.__objectNames[46] = "obj_asteroidshardtrade_earth";
global.__objectNames[47] = "obj_tradeins_vopra";
global.__objectNames[48] = "obj_refills_vopra";
global.__objectNames[49] = "obj_upgrades_vopra";
global.__objectNames[50] = "obj_shop_back_vopra";
global.__objectNames[51] = "obj_ach_back";
global.__objectNames[52] = "obj_ach_next";
global.__objectNames[53] = "obj_yes_mission2";
global.__objectNames[54] = "obj_no_mission2";
global.__objectNames[55] = "obj_fragement";
global.__objectNames[56] = "obj_savepoint_space";
global.__objectNames[57] = "obj_mana";
global.__objectNames[58] = "obj_chest_closed";
global.__objectNames[59] = "obj_chest_opening";
global.__objectNames[60] = "obj_chest_opened";
global.__objectNames[61] = "obj_health";
global.__objectNames[62] = "obj_spacecoin";
global.__objectNames[63] = "obj_tree";
global.__objectNames[64] = "obj_asteroidHUD";
global.__objectNames[65] = "collectables_display";
global.__objectNames[66] = "obj_asteroid1";
global.__objectNames[67] = "obj_asteroid2";
global.__objectNames[68] = "obj_asteroid3";
global.__objectNames[69] = "obj_asteroid4";
global.__objectNames[70] = "obj_asteroid5";
global.__objectNames[71] = "obj_asteroidshard1";
global.__objectNames[72] = "obj_asteroidshard2";
global.__objectNames[73] = "obj_asteroidshard3";
global.__objectNames[74] = "obj_asteroidshard4";
global.__objectNames[75] = "obj_asteroidshard5";
global.__objectNames[76] = "obj_teleporter";
global.__objectNames[77] = "obj_vendor";
global.__objectNames[78] = "obj_bullet";
global.__objectNames[79] = "obj_enemybullet";
global.__objectNames[80] = "obj_ship_earth";
global.__objectNames[81] = "obj_ship_earthout";
global.__objectNames[82] = "obj_ship_earthin";
global.__objectNames[83] = "obj_ship_vopra";
global.__objectNames[84] = "obj_ship_vopraout";
global.__objectNames[85] = "obj_ship_voprain";
global.__objectNames[86] = "obj_ship_calia";
global.__objectNames[87] = "obj_ship_caliaout";
global.__objectNames[88] = "obj_ship_caliain";
global.__objectNames[89] = "obj_ship_credits";
global.__objectNames[90] = "landingpad_0";
global.__objectNames[91] = "landingpad_1";
global.__objectNames[92] = "obj_solid_block";
global.__objectNames[93] = "obj_lt_openspace";
global.__objectNames[94] = "obj_lt_earthsector";
global.__objectNames[95] = "obj_lt_opronesector";
global.__objectNames[96] = "obj_lt_voprasector";
global.__objectNames[97] = "obj_lt_caliasector";
global.__objectNames[98] = "obj_lt_zeriasector";
global.__objectNames[99] = "obj_lt_gerussector";
global.__objectNames[100] = "obj_lt_asprionsector";
global.__objectNames[101] = "obj_lt_ocreonsector";
global.__objectNames[102] = "cave_entrance1";
global.__objectNames[103] = "pathcorner_tile";
global.__objectNames[104] = "path_tile";
global.__objectNames[105] = "rockwall";
global.__objectNames[106] = "rockend";
global.__objectNames[107] = "rockend_corner";
global.__objectNames[108] = "rockend_side";
global.__objectNames[109] = "rock_insidecorner";
global.__objectNames[110] = "waterfall_middle";
global.__objectNames[111] = "waterfall_bottom";
global.__objectNames[112] = "waterfall_top";
global.__objectNames[113] = "water_tile";
global.__objectNames[114] = "pathend";
global.__objectNames[115] = "shop_earth";
global.__objectNames[116] = "earth_cave_exit";
global.__objectNames[117] = "ach001";
global.__objectNames[118] = "obj_header";
global.__objectNames[119] = "cutscene1_fadeout";
global.__objectNames[120] = "obj_menuholo";
global.__objectNames[121] = "shiplevel";
global.__objectNames[122] = "collectable_hud";
global.__objectNames[123] = "obj_wolfmask";
global.__objectNames[124] = "obj_caveterrain";
global.__objectNames[125] = "obj_earth1ctrl";
global.__objectNames[126] = "obj_earth1back";
global.__objectNames[127] = "obj_claimearth1";
global.__objectNames[128] = "obj_earth2char";
global.__objectNames[129] = "obj_earth2points20";
global.__objectNames[130] = "obj_earth2points19";
global.__objectNames[131] = "obj_earth2points18";
global.__objectNames[132] = "obj_earth2points17";
global.__objectNames[133] = "obj_earth2points16";
global.__objectNames[134] = "obj_earth2points15";
global.__objectNames[135] = "obj_earth2points14";
global.__objectNames[136] = "obj_earth2points13";
global.__objectNames[137] = "obj_earth2points12";
global.__objectNames[138] = "obj_earth2points11";
global.__objectNames[139] = "obj_earth2points10";
global.__objectNames[140] = "obj_earth2points9";
global.__objectNames[141] = "obj_earth2points8";
global.__objectNames[142] = "obj_earth2points7";
global.__objectNames[143] = "obj_earth2points6";
global.__objectNames[144] = "obj_earth2points5";
global.__objectNames[145] = "obj_earth2points4";
global.__objectNames[146] = "obj_earth2points3";
global.__objectNames[147] = "obj_earth2points2";
global.__objectNames[148] = "obj_earth2points1";
global.__objectNames[149] = "obj_earth2text";
global.__objectNames[150] = "obj_claimearth2";
global.__objectNames[151] = "obj_earth2back";
global.__objectNames[152] = "obj_earth2retry";
global.__objectNames[153] = "obj_earth3data";
global.__objectNames[154] = "obj_earth3char";
global.__objectNames[155] = "obj_earth3text";
global.__objectNames[156] = "obj_claimearth3";
global.__objectNames[157] = "obj_earth3back";
global.__objectNames[158] = "obj_vopra1_back";
global.__objectNames[159] = "skills";
global.__objectNames[160] = "mega_var";
global.__objectNames[161] = "skill_popups";
global.__objectNames[162] = "gp_pause";
global.__objectNames[163] = "gp_pause_boss1";
global.__objectNames[164] = "gp_pauseearth";
global.__objectNames[165] = "gp_menu";
global.__objectNames[166] = "gp_explore";
global.__objectNames[167] = "gp_map";
global.__objectNames[168] = "gp_levelups";
global.__objectNames[169] = "gp_harvlevelmax";
global.__objectNames[170] = "gp_earth";
global.__objectNames[171] = "gp_mission2_choice";
global.__objectNames[172] = "gp_shopearth";
global.__objectNames[173] = "gp_tradeinsearth";
global.__objectNames[174] = "gp_shopvopra";
global.__objectNames[175] = "gp_tradeinsvopra";
global.__objectNames[176] = "obj_menucontroller";
global.__objectNames[177] = "obj_HUDcontroller";
global.__objectNames[178] = "obj_spacesoundctrl";
global.__objectNames[179] = "obj_mapcontroller";
global.__objectNames[180] = "obj_skillsdraw";
global.__objectNames[181] = "shop_values";
global.__objectNames[182] = "shop_draw";
global.__objectNames[183] = "altpause_controller";
global.__objectNames[184] = "altpause_earth";
global.__objectNames[185] = "screenshot_text";
global.__objectNames[186] = "earthcontroller";
global.__objectNames[187] = "obj_noid_draw";
global.__objectNames[188] = "credits_controller";
global.__objectNames[189] = "object149";
global.__objectNames[190] = "cutscene1_1_tl";
global.__objectNames[191] = "cutscene1_2_tl";
global.__objectNames[192] = "cutscene2_1_tl";
global.__objectNames[193] = "cutscene2_2_tl";
global.__objectNames[194] = "cutscene_m2_1_tl";
global.__objectNames[195] = "cutscene_m2_2_tl";
global.__objectNames[196] = "cutscene_m2_3_tl";
global.__objectNames[197] = "cutscene_controller";
global.__objectNames[198] = "mission_completion";
global.__objectNames[199] = "boss1_healthbar";
global.__objectNames[200] = "planetbar_hud";
global.__objectNames[201] = "quest_earth";
global.__objectNames[202] = "game_saver";
global.__objectNames[203] = "obj_ach001";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for